name: Flask CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml run webapp python -m pytest  # Add tests later

      # Use appleboy/ssh-action@v0.1.15 (latest version as of 2023)
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.15
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your-project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
